### ISSUE TITLE
icon for exchangego

### ISSUE THREAD

**Issue by somratking420** [Broadroad/ExchangeGo#1]
Hi@broadroad, I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by Broadroad** [comment]
Sure, @somratking420. It will be great if you can help it.

**Comment by somratking420** [comment]
Hello,@BROADROAD,,
Good Day, i make a logo icon for your project.I make a 2 logo for you.Which logo do you like? If you want to use this logo in your project, then comment below, I will give you the source file.
![exxx](https://user-images.githubusercontent.com/40878798/42552383-d09cce66-84fd-11e8-9182-ff5ad2e6655f.png)

**Comment by Broadroad** [comment]
hi @somratking420,  Thank you very much. I 'd like 2. Because this project not only want to be used with dollar or cny, but also other currency. such as JPY.

**Comment by somratking420** [comment]
hi @Broadroad , I've uploaded the logo to the drive, this is the link.https://drive.google.com/open?id=1jV4B68H1NuV8GGE8UgQzZxfqsZ0sZOnn


and also I have sent a pull request for you, check #2
